name: Deploy to Dev

on:
  pull_request:
    branches: [main]
    types: [opened]
  pull_request_target:
    branches: [main]
    types: [opened]
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "deploy inside server"
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "3.86.229.237"
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY }}
          port: "22"
          script_stop: true
          script: |
            echo "I AM DEPLOYING YAHOOO!"
            echo runSuccess > /tmp/run.txt
            echo `whoami`
